CREATE TABLE IF NOT EXISTS cursos (
  id VARCHAR PRIMARY KEY,
  curso VARCHAR(50) DEFAULT NULL,
  modalidad VARCHAR(50) DEFAULT NULL,
  seccion VARCHAR(50) DEFAULT NULL,
  jornada VARCHAR(50) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS fichas (
  id VARCHAR PRIMARY KEY,
  nombre VARCHAR(50) DEFAULT NULL,
  apellidos VARCHAR(50) DEFAULT NULL,
  direccion VARCHAR(50) DEFAULT NULL,
  fechaNacimiento TIME NOT NULL,
  sexo VARCHAR(50) NOT NULL,
  padre VARCHAR(50) NOT NULL,
  madre VARCHAR(50) NOT NULL,
  fechaMatricula TIME NOT NULL,
  idCurso VARCHAR NOT NULL REFERENCES cursos(id)
) ;

CREATE TABLE IF NOT EXISTS maestros (
  id VARCHAR PRIMARY KEY,
  nombre VARCHAR(50) DEFAULT NULL,
  apellidos VARCHAR(50) DEFAULT NULL,
  direccion VARCHAR(50) DEFAULT NULL,
  telefono VARCHAR(50) NOT NULL,
  mail VARCHAR(50) NOT NULL
) ;

CREATE TABLE IF NOT EXISTS materias (
  id VARCHAR PRIMARY KEY,
  materia VARCHAR(50) DEFAULT NULL,
  idCurso VARCHAR NOT NULL REFERENCES cursos(id),
  idMaestro VARCHAR NOT NULL REFERENCES maestros(id)
) ;

CREATE TABLE IF NOT EXISTS notas (
  idEstudiante VARCHAR NOT NULL,
  idCurso VARCHAR NOT NULL,
  idMateria VARCHAR NOT NULL,
  PRIMARY KEY (idEstudiante, idCurso, idMateria),
  examen_1 FLOAT DEFAULT NULL,
  examen_2 FLOAT DEFAULT NULL,
  examen_3 FLOAT DEFAULT NULL,
  examen_4 FLOAT DEFAULT NULL,
  promedio FLOAT DEFAULT NULL,
  recuperacion_1 FLOAT DEFAULT NULL,
  recuperacion_2 FLOAT DEFAULT NULL
 ) ;

 CREATE TABLE IF NOT EXISTS conceptos (
   id VARCHAR PRIMARY KEY,
   concepto VARCHAR(50) DEFAULT NULL,
   precio FLOAT DEFAULT NULL
 ) ;

 CREATE TABLE IF NOT EXISTS cobros(
   id VARCHAR PRIMARY KEY,
   fechaCobro TIME DEFAULT NULL,
   precio FLOAT DEFAULT NULL,
   cantidad INTEGER DEFAULT NULL,
   total FLOAT DEFAULT NULL,
   idEstudiante VARCHAR NOT NULL REFERENCES fichas(id), 
  idConcepto VARCHAR NOT NULL REFERENCES conceptos(id)
 );

 CREATE TABLE IF NOT EXISTS conceptoPagos(
   id VARCHAR PRIMARY KEY,
   concepto VARCHAR DEFAULT NULL,
   precio FLOAT DEFAULT NULL
 );

  CREATE TABLE IF NOT EXISTS empleados(
    id VARCHAR PRIMARY KEY,
  nombre VARCHAR(50) DEFAULT NULL,
  apellidos VARCHAR(50) DEFAULT NULL,
  direccion VARCHAR(50) DEFAULT NULL,
  telefono VARCHAR(50) NOT NULL,
  mail VARCHAR(50) NOT NULL
  );

  CREATE TABLE IF NOT EXISTS jornada(
    id VARCHAR PRIMARY KEY,
    jornada VARCHAR DEFAULT NULL
  );


  CREATE TABLE IF NOT EXISTS proveedores(
    id VARCHAR PRIMARY KEY,
    nombre VARCHAR DEFAULT NULL,
    direccion VARCHAR DEFAULT NULL,
    telefono VARCHAR DEFAULT NULL
  );

  CREATE TABLE IF NOT EXISTS producto(
    id VARCHAR PRIMARY KEY,
    producto VARCHAR DEFAULT NULL,
    precioCosto FLOAT DEFAULT NULL,
    utilidad FLOAT DEFAULT NULL,
    precioVenta FLOAT DEFAULT NULL,
    idProveedor VARCHAR NOT NULL REFERENCES proveedores(id)
  );

  CREATE TABLE IF NOT EXISTS ventas(
    id VARCHAR PRIMARY KEY,
    idEmpleado VARCHAR NOT NULL REFERENCES empleados(id),
    idEstudiante VARCHAR NOT NULL REFERENCES fichas(id),
    fechaVenta TIME NOT NULL
  );


